services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./kind/kubeconfig-docker:/root/.kube/config:ro
      - ./manifests:/app/manifests:ro
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - roo-network
      - kind
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - roo-network
    restart: unless-stopped

networks:
  roo-network:
    driver: bridge
  kind:
    external: true
