apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode-server
  namespace: proj-4g72fu
  labels:
    app: vscode-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vscode-server
  template:
    metadata:
      labels:
        app: vscode-server
    spec:
      containers:
      - name: vscode-server
        image: gitpod/openvscode-server:latest
        ports:
        - containerPort: 3000
        env:
        - name: OPENVSCODE_SERVER_ROOT
          value: "/home/workspace"
        - name: ALLOWED_EXTENSIONS
          value: "roo-code"
        command:
        - /bin/bash
        - -c
        - |
          # Download and install Roo Code extension
          echo "📦 Installing Roo Code extension..."
          curl -L -o /tmp/roo-code.vsix "https://github.com/RooCodeInc/Roo-Code/releases/download/v3.19.3/roo-cline-3.19.3.vsix" || \
          echo "⚠️  Could not download Roo Code extension, continuing without it..."

          # Install extension if downloaded
          if [ -f /tmp/roo-code.vsix ]; then
            echo "Installing Roo Code extension..."
            /home/.openvscode-server/bin/openvscode-server \
              --install-extension /tmp/roo-code.vsix \
              --force
            echo "Extension installed successfully"
          fi

          # Start OpenVSCode Server
          echo "Starting OpenVSCode Server..."
          /home/.openvscode-server/bin/openvscode-server \
            --host 0.0.0.0 \
            --port 3000 \
            --without-connection-token \
            --accept-server-license-terms \
            --connection-secret-file /dev/null \
            --server-base-path /proj-4g72fu
        volumeMounts:
        - name: workspace
          mountPath: /home/workspace
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: workspace
        emptyDir: {}
